apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: r-logs-dev

resources:
  - namespace.yaml
  - ../../base/backend

images:
  - name: r-log-backend
    newName: r-log-backend
    newTag: dev

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
