apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: r-logs-prod

resources:
  - namespace.yaml
  - ../../base/backend

images:
  - name: r-log-backend
    newName: registry.example.com/r-log-backend
    newTag: latest

patches:
  - path: deployment-patch.yaml
